version: '3.8'

services:
  kakeydb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    # volumes:
    #   - ../20240216.05.07.07.sql:/docker-entrypoint-initdb.d/a.sql   <---- NEED DUMP FILE
    networks:
      otel:

  kakey-web:
    build: ..
    ports:
      - 6080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "db=server=kakeydb;user id=postgres;database=postgres;password=password;"
    networks:
      otel:
      
  blackbox:
    image: prom/blackbox-exporter:v0.23.0
    container_name: blackbox
    restart: unless-stopped
    ports:
      - 6015:9115
    volumes:
      - ./blackbox.yml:/etc/blackbox/blackbox.yml
    command: --config.file=/etc/blackbox/blackbox.yml
    networks:
      otel:


  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    ports:
      - 6090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - blackbox
    networks:
      otel:

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki.yml:/etc/loki/local-config.yaml
    ports:
      - 3215:3100
    networks:
      otel:
      
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel.yml:/etc/otel-collector-config.yaml
    networks:
      otel:
    depends_on:
    - zipkin

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    ports:
      - 6086:3000
    depends_on:
      - prometheus
      - loki      
    networks:
      otel:

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 5411:9411
    networks:
      otel:

  proxy:
    image: nginx
    ports:
      - 5467:80
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - grafana
    networks:
      otel:

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=kakeysbakery.duckdns.org
      - DUCKDNSTOKEN=1257e8b5-c71f-4f50-9232-96bc999385ee
      - VALIDATION=duckdns
      - STAGING=true
    volumes:
      - swag_data:/config
      - ./nginx-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 1919:443
    restart: unless-stopped
    networks:
      otel:
      
networks:
  otel:

volumes:
  grafana-data:
  loki:
  prometheus:
  zipkin:  
  swag_data:  