apiVersion: v1
kind: Service
metadata:
  namespace: kakey-1
  name: otel-collector-service

apiVersion: v1
kind: Service
metadata:
  namespace: kakey-1
  name: otel-collector-service
spec:
  type: ClusterIP
  selector:
    app: kakey-otel-collector
  ports:
    - port: 80
      targetPort: 8080