apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${NAMESPACE}
  name: kakey-grafana-deployment
  labels:
    app: kakey-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kakey-grafana
  template:
    metadata:
      labels:
        app: kakey-grafana
    spec:
      containers:
      - name: kakey-grafana
        image: grafana/grafana:9.4.7
        ports:
        - containerPort: 3000
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources/datasource.yml
          subPath: grafana-datasource.yml
        - name: dashboards
          mountPath: /etc/grafana/provisioning/dashboards/dashboard.yml
          subPath: dashboard.yml
      volumes:
      - name: datasources
        configMap:
          name: grafana-datasource-config
      - name: dashboards
        configMap:
          name: grafana-dashboard-config
