apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: kakey-grafana-ingress
    annotations:
      cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-alex-production
spec:
  tls:
  - hosts:
    - grafana.kakeysbakery.alex-kube.duckdns.org
    secretName: grafana-kakeysbakery-1-kube-tls-production
  ingressClassName: nginx
  rules:
  - host: grafana.kakeysbakery.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kakey-grafana-service
            port:
              number: 3000