{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Most popular pages",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"metrics\", otel_scope_name=\"KakeyMetrics\", __name__=~\".*count.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregated Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg_over_time(up{job=\"blackbox\", instance=\"http://kakeysbakery.duckdns.org:80/health\"}[1w])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum({__name__=\"kestrel_active_connections\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg_over_time(up{job=\"blackbox\", instance=\"http://kakeysbakery.duckdns.org:80/health\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({job=\"metrics\", otel_scope_name=\"KakeyMetrics\", __name__=~\".*error.*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}