name: (On Merge) Pull Request Environment (Telemetry and Run Site on K8s Cluster)

on:
  pull_request:
    types: [closed]
env:
  CONFIGURATION: Release
  WORKING_DIRECTORY: KakeysBakery
jobs:
  kubernetes:
    runs-on: self-hosted
    needs: Build
    steps:
    - name: Kubectl Up
      run: |
        export PULL_REQUEST_ID=${{ github.event.pull_request.number }}
        export NAMESPACE="kakey-pr-$PULL_REQUEST_ID"
        echo "Pull request id $PULL_REQUEST_ID"

        kubectl delete namespace $NAMESPACE