name: (On PR) Pull Request Environment (Telemetry and Run Site on K8s Cluster)

on:
  pull_request:
    types: [opened]
env:
  CONFIGURATION: Release
  WORKING_DIRECTORY: KakeysBakery
jobs:
  Build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      run: |
          dotnet restore "${{ env.WORKING_DIRECTORY }}"

    - name: Lint
      run: |
          cd KakeysBakery
          dotnet format --verify-no-changes --severity warn
    - name: Build
      run: |
          dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore /warnaserror

    - name: Run Test Suite
      run: |
        cd ./KakeysBakery.Tests/
        dotnet test

  kubernetes:
    runs-on: self-hosted
    needs: Build
    steps:
    - name: Kubectl Up
      run: |
        export PULL_REQUEST_ID=${{ github.event.pull_request.number }}
        export NAMESPACE="kakey-pr-$PULL_REQUEST_ID"
        echo "Pull request id $PULL_REQUEST_ID"

        kubectl create namespace $NAMESPACE || true

        docker build -t 144.17.92.12:5000/kakey-1/blazor-web:$GITHUB_RUN_ID .
        docker push 144.17.92.12:5000/kakey-1/blazor-web:$GITHUB_RUN_ID

        cd KakeysBakery.Tests
          kubectl -n $NAMESPACE delete configmap blazor-web-postgres-init || true
          kubectl -n $NAMESPACE create configmap blazor-web-postgres-init --from-file=Apr15ddl.sql
        cd ../

        cd Telemetry/kube-configs
          kubectl -n $NAMESPACE delete configmap grafana-datasource-config || true
          kubectl -n $NAMESPACE create configmap grafana-datasource-config --from-file=grafana-datasource.yml
        
          kubectl -n $NAMESPACE delete configmap otel-config || true
          kubectl -n $NAMESPACE create configmap otel-config --from-file=otel-collector-config.yml
        cd ../../

        kubectl -n $NAMESPACE delete svc blazor-web-db-service || true
        kubectl -n $NAMESPACE delete ingress kakey-blazor-ingress || true
        kubectl -n $NAMESPACE delete deployment blazor-web-db-deployment || true
        kubectl -n $NAMESPACE delete deployment kakey-blazor-web-deployment || true

        for file in ./Telemetry/kube/*; do
          echo "Applying $file"
          cat $file | envsubst | kubectl apply -f -
        done